name: Bug Report
description: Report a bug you encountered with the Okta Auth JS SDK
labels: [ bug ]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug
      description: |
        Please be as detailed as possible. This will help us address the bug in a timely manner.
      placeholder: What is expected to happen... What is the actual behavior?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps?
      description: |
        Please provide as much detail as possible to help us reproduce your bug.
        A reproduction repo is very helpful for us as well.
    validations:
      required: true

  - type: textarea
    id: sdkVersion
    attributes:
      label: SDK Versions
      description: |
        Output of `npx envinfo --system --npmPackages '{@okta/*,}' --binaries --browsers`
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information?
